# 数据源配置
spring:
  application:
    name: mall-tiny-mybatis-generator
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

# MyBatis mapper.xml路径配置
mybatis:
  mapper-locations:
    - classpath:dao/*.xml # 自定义的目录
    - classpath*:com/**/mapper/*.xml # 自动生成的目录